Events.com/Controllers/EventDetailsController.cs
namespace SoftServeEvents.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using SoftServeEvents.Models;

    /// <summary>
    /// Represents the Event page methods
    /// </summary>
    public class EventDetailsController : Controller
    {
        /// <summary>
        /// Database context for interaction with database
        /// </summary>
        EventsDbEntities db = new EventsDbEntities();

        /// <summary>
        /// Construct logic of the Show Event page 
        /// </summary>
        /// <param name="placeId">Identifier of the Place row</param>
        /// <param name="currentEvent">Event which is presented</param>
        /// <returns>Returns a control that acts as a container</returns>
        public ActionResult ShowEvent(int placeId, string currentEvent)
        {
            var place = this.db.Places.Include("Events").Single(e => e.Id == placeId);
            ViewBag.CurrentEvent = currentEvent;
            return View(place);
        }
    }
}

Events.com/Controllers/HomeController.cs
namespace SoftServeEvents.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using SoftServeEvents.Models;
    using System.Collections;

    /// <summary>
    /// Represents methods for processing homepage
    /// </summary>
    public class HomeController : Controller
    {
        /// <summary>
        /// Using for interaction with database 
        /// </summary>
        DbEventManager dbManager = new DbEventManager();

        /// <summary>
        /// Constructs the Index page 
        /// </summary>
        /// <returns>Returns a control that acts as a container</returns>
        public ActionResult Index()
        {
            GenresAndEventsContainer container = this.dbManager.GetAllPlacesoOfEvent();
            return View(container);
        }

        /// <summary>
        /// Constructs the Browse page 
        /// </summary>
        /// <param name="genre">New genre to render</param>
        /// <returns>Returns a control that acts as a container</returns>
        public ActionResult Browse(string genre)
        {
            GenresAndEventsContainer container = this.dbManager.GetAllEventsOfCurrentGenre(genre);
            return View(container);
        }
    }
}

Events.com/Views/Home/Browse.cshtml
@model SoftServeEvents.Models.GenresAndEventsContainer
@{
    ViewBag.Title = "Browse";
}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <p class="lead">Shop Name</p>
            <div class="list-group">
                @foreach (var genre in Model.Genres)
                {
                    @Html.ActionLink(genre.Title, "Browse", new { genre = genre.Title }, new { @class = "list-group-item" })
                }
            </div>
        </div>
        <div class="col-md-9">
            <div class="row">
                @foreach (var myEvent in Model.Genre.Events)
                {
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="~/Content/Images/event.jpg" alt="" />
                            <div class="caption">
                                <h4 class="pull-right">$24.99</h4>
                                <h4>
                                    @Html.ActionLink(@myEvent.Title, "ShowEvent", "EventDetails", new { placeId = myEvent.PlaceId, currentEvent = myEvent.Title }, null)
                                </h4>
                                <p>
                                    See more snippets like this online store item at.
                                    See more snippets like this online store item at.
                                    See more snippets like this online store item at.
                                </p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">15 reviews</p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Events.com/Views/Home/Details.cshtml
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

Events.com/Views/Home/Index.cshtml
@model SoftServeEvents.Models.GenresAndEventsContainer
@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <p class="lead">Shop Name</p>
            <div class="list-group">
                @foreach (var genre in Model.Genres)
                {
                    @Html.ActionLink(genre.Title, "Browse", new { genre = genre.Title }, new { @class = "list-group-item" })
                }
            </div>
        </div>
        <div class="col-md-9">
            <!--
            <div class="row carousel-holder">
                <div class="col-md-12">
                  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="slide-image" src="http://placehold.it/800x300" alt="" />
                            </div>
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>

                </div>
            </div>
            -->
            <div class="row">
                @foreach (var myEvent in Model.Events)
                { 
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="~/Content/Images/event.jpg" alt="" />
                        <div class="caption">
                            <h4 class="pull-right">$24.99</h4>
                            <h4>
                                @Html.ActionLink(@myEvent.Title, "ShowEvent", "EventDetails", new { placeId = myEvent.PlaceId, currentEvent = myEvent.Title }, null)
                            </h4>
                            <p>See more snippets like this online store item at.
                                See more snippets like this online store item at.
                                See more snippets like this online store item at.</p>
                        </div>
                        <div class="ratings">
                            <p class="pull-right">15 reviews</p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star-empty"></span>
                        </div>
                    </div>
                </div>
                }
            </div>      
        </div>
    </div>
</div>